In [3]:
import numpy as np

rows = 50
columns = 50

matrix = np.random.random((rows, columns))

np.savetxt('random_matrix.csv', matrix, delimiter=',', fmt='%.6f')

print("Data file 'random_matrix.csv' created successfully.")

Data file 'random_matrix.csv' created successfully.


In [4]:
import numpy as np

def assign_subsequent_rows(matrix):
    matrix = np.array(matrix)
    first_row = matrix[0, :]
    matrix[1:, :] = first_row
    return matrix

if __name__ == "__main__":

    matrix = np.loadtxt('random_matrix.csv', delimiter=',')

    print("Original Matrix:")
    print(matrix)

    modified_matrix = assign_subsequent_rows(matrix)

    print("\nModified Matrix:")
    print(modified_matrix)

    np.savetxt('modified_matrix.csv', modified_matrix, delimiter=',', fmt='%.6f')
    print("Modified matrix saved to 'modified_matrix.csv'.")

Original Matrix:
[[0.96097  0.948104 0.932531 ... 0.152217 0.767838 0.946898]
 [0.738494 0.375745 0.59497  ... 0.490792 0.109186 0.519919]
 [0.875968 0.705494 0.095486 ... 0.084718 0.366768 0.768559]
 ...
 [0.989029 0.655946 0.115229 ... 0.555604 0.088757 0.114828]
 [0.612488 0.716413 0.492956 ... 0.432032 0.109701 0.797019]
 [0.021598 0.16512  0.215963 ... 0.929439 0.313108 0.176335]]

Modified Matrix:
[[0.96097  0.948104 0.932531 ... 0.152217 0.767838 0.946898]
 [0.96097  0.948104 0.932531 ... 0.152217 0.767838 0.946898]
 [0.96097  0.948104 0.932531 ... 0.152217 0.767838 0.946898]
 ...
 [0.96097  0.948104 0.932531 ... 0.152217 0.767838 0.946898]
 [0.96097  0.948104 0.932531 ... 0.152217 0.767838 0.946898]
 [0.96097  0.948104 0.932531 ... 0.152217 0.767838 0.946898]]
Modified matrix saved to 'modified_matrix.csv'.


In [5]:
def group_elements(matrix, num_groups):
  flatt = matrix.flatten()
  sorted_flatt = np.sort(flatt)
  group_elements = np.array_split(sorted_flatt, num_groups)
  rows = len(group_elements)
  columns = max(len(group) for group in group_elements)
  grouped_matrix = np.full((rows, columns), np.nan)
  for i, group in enumerate(group_elements):
    grouped_matrix[i, :len(group)] = group
  return grouped_matrix

if __name__ == "__main__":
  rows = 5
  columns = 5
  matrix = np.random.random((rows, columns))
print("Original Matrix:")
print(matrix)
num_groups = 3
grouped_matrix = group_elements(matrix, num_groups)
print("\nGrouped Matrix:")
print(grouped_matrix)

Original Matrix:
[[0.95797191 0.71165747 0.04870981 0.85658701 0.55570968]
 [0.06126071 0.83302384 0.30066237 0.31175887 0.15519379]
 [0.19144305 0.65036092 0.93780961 0.29057993 0.28970308]
 [0.17240423 0.30346032 0.64506225 0.19625595 0.76286344]
 [0.5689861  0.18972394 0.54943647 0.49226734 0.29450926]]

Grouped Matrix:
[[0.04870981 0.06126071 0.15519379 0.17240423 0.18972394 0.19144305
  0.19625595 0.28970308 0.29057993]
 [0.29450926 0.30066237 0.30346032 0.31175887 0.49226734 0.54943647
  0.55570968 0.5689861         nan]
 [0.64506225 0.65036092 0.71165747 0.76286344 0.83302384 0.85658701
  0.93780961 0.95797191        nan]]


In [6]:
def add_matrices(matrix1, matrix2):
    return np.add(matrix1, matrix2)

def subtract_matrices(matrix1, matrix2):
    return np.subtract(matrix1, matrix2)

if __name__ == "__main__":
    matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

    print("Matrix 1:")
    print(matrix1)

    print("\nMatrix 2:")
    print(matrix2)

    sum_matrix = add_matrices(matrix1, matrix2)
    print("\nSum of Matrix 1 and Matrix 2:")
    print(sum_matrix)

    difference_matrix = subtract_matrices(matrix1, matrix2)
    print("\nDifference of Matrix 1 and Matrix 2:")
    print(difference_matrix)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Sum of Matrix 1 and Matrix 2:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Difference of Matrix 1 and Matrix 2:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [7]:
def create_even_odd_matrix(n):
    matrix = np.zeros((n, n), dtype=int)

    even = 0
    odd = 1

    for i in range(n):
        for j in range(n):
            if (i + j) % 2 == 0:
                matrix[i, j] = even
                even += 2
            else:
                matrix[i, j] = odd
                odd += 2

    return matrix

if __name__ == "__main__":
    n = int(input("Enter the size of the matrix (n): "))
    matrix = create_even_odd_matrix(n)
    print("Generated Matrix:")
    print(matrix)

Enter the size of the matrix (n): 5
Generated Matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [11]:
def row_wise_sum(tuple_matrix):
    row_sums = []

    for row in tuple_matrix:
        row_sum = sum(row)
        row_sums.append(row_sum)

    return row_sums

if __name__ == "__main__":
    tuple_matrix = (
        (1, 2, 3),
        (4, 5, 6),
        (7, 8, 9),
        (10, 11, 12)
    )

    print("Original Tuple Matrix:")
    for row in tuple_matrix:
        print(row)

    row_sums = row_wise_sum(tuple_matrix)

    print("\nRow-wise Sums:")
    for i, row_sum in enumerate(row_sums):
        print(f"Row {i+1}: {row_sum}")

Original Tuple Matrix:
(1, 2, 3)
(4, 5, 6)
(7, 8, 9)
(10, 11, 12)

Row-wise Sums:
Row 1: 6
Row 2: 15
Row 3: 24
Row 4: 33
